name: Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      
      - name: Sync dependencies
        run: |
          uv sync
      
      - name: Run training pipeline
        run: |
          uv run app/training_endpoint.py
        env:
          # Add any environment variables needed for training
          PYTHONUNBUFFERED: 1
      
      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: trained-model
          path: |
            models/
            *.pkl
            *.joblib
          retention-days: 30